#! /bin/bash
# script to build sitebuilder local site
# Run it on your document root like :
# $ makedrupal <foldername> <make.file location> <profile>
# echo -e '\E[37;44m'"\033[1mContact List\033[0m"
# set -x #debug option

# COL_BLUE="\x1b[34;01m"
# COL_RESET="\x1b[39;41;01m"

build_site() {
	echo "*** Building $1 app..."
	# Make site folder.
	mkdir -p $1

	if [ ! -f $2 ]; then
		echo "**! make file does not exist"
	else
		# absolute path of makefile
		# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

		# Use Homebrew to install coreutils package for greadlink command.
		# TODO alias readlink=greadlink for consistency
		makefile=$(greadlink -m $2)
		echo "*** Using $makefile makeFile..."
		# default profile if none given
		profile="standard"
		if [ ! -n $3 ]; then
			echo "*** Using default profile"
		else
			profile=$3
			echo "**> Installing using $profile profile"
		fi
		echo "**> Opening $1..."
		cd $1
		drush make --working-copy --no-gitinfofile $makefile -y

		echo "*** Installing Drupal..."
		drush si --account-pass=admin --clean-url=1 --db-url=mysql://root:root@127.0.0.1:8889/$1 $profile -y # --uri=http://book.local/$1
		echo -e "*** Launching installation..."

		# open in browser
		# TODO auto document root
		open http://127.0.0.1/$1
	fi
}
# Strip slash if any in dest path
target=${1%/}

if [ ! -n $1 ]; then
	echo "**!  Enter a directory name!"
elif [ -d $target ]; then
	echo "**! $target project allready exists."
	read -p "**! Would you like to replace the $target project files and database? (y/n)? " -n 1 -r
	echo    # (optional) move to a new line
	if [[ ! $REPLY =~ ^[Yy]$ ]]
	then
	    echo "Terminated."
	    exit 1
	else
		sudo rm -rf $target
		build_site $target $2 $3
	fi
else
	build_site $target $2 $3
fi
